FuckYouList/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Fuck(models.Model):
    author = models.ForeignKey(User)
    message = models.CharField(max_length=1000)
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    score = models.IntegerField()



class Comment(models.Model):
    author = models.ForeignKey(User)
    message = models.CharField(max_length=1000)
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    fuck = models.ForeignKey(Fuck)


class Vote(models.Model):
    voter = models.ForeignKey(User)
    value = models.IntegerField()
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

FuckYouList/forms.py
from django import forms
from django.contrib.auth.models import AnonymousUser, User
from models import Fuck, Comment

class FuckForm(forms.ModelForm):
    class Meta:
        model = Fuck
        exclude = ('author',)
        score = forms.IntegerField(max_value=10,min_value=1,attrs={'class':'slider'})


class CommentForm(forms.ModelForm):
    class Meta:
            model = Comment
            exclude = {'author',}

FuckYouList/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.views.generic import CreateView, UpdateView
from FuckYouList.models import Fuck
from FuckYouList.forms import FuckForm
import smtplib
from email.mime.text import MIMEText


class FuckCreate(CreateView):
    model = Fuck
    form_class = FuckForm
    template_name = "newfuck.html"

    def get(self, request, *args, **kwargs):
        return super(FuckCreate, self).get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        return super(FuckCreate, self).post(request, *args, **kwargs)

    def form_valid(self, form):
        obj = form.save(commit=False)
        if not self.request.user.is_anonymous():
            obj.author = self.request.user
        else:
            obj.author = User.objects.get_or_create(id=69)[0]
        obj.save()

        return HttpResponseRedirect(self.success_url)

class FuckEdit(UpdateView):
    model = Fuck
    form_class = FuckForm
    template_name = "newfuck.html"

    def get(self, request, *args, **kwargs):
        if request.user == self.object.author:
            return super(FuckEdit, self).get(request, *args, **kwargs)
        else:
            return HttpResponseRedirect(self.success_url)

    def post(self, request, *args, **kwargs):
        if request.user == self.object.author:
            return super(FuckEdit, self).post(request, *args, **kwargs)
        else:
            return HttpResponseRedirect(self.success_url)


class UserCreate(CreateView):
    model = User
    form_class = UserCreationForm
    template_name = 'registration/create_user.html'


    #Not working, at all.
    def send_reg_email(self, obj):
        msg = MIMEText("A new user with name of " + obj.username + "has been created in the Fuck You List")
        msg["Subject"] = "new fuck you list user"
        msg["From"] = "amarano@gmail.com"
        msg["To"] = "amarano@gmail.com"
        s = smtplib.SMTP("localhost")
        s.sendmail("amarano@gmail.com", ["amarano@gmail,com"], msg.as_string())
        s.quit()

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.is_active = False
        obj.save()

        try:
            self.send_reg_email(obj)
        except:
            return

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>Fuck You</title>
    <link href='http://fonts.googleapis.com/css?family=Monda' rel='stylesheet' type='text/css'>
    <link href="{{ STATIC_URL }}Includes/fuckyoulist.css" rel="stylesheet" type="text/css">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js" type="text/javascript"></script>
    <script>
        $(document).ready(function () {
            $(".AddCommentButton").on("click", function (e) {
                e.preventDefault();
                $(this).next('.addComment').show();
            });

            $(".SubmitComment").on("click", function (e) {
                var m = $(this).prevAll('.TextAreaComment').val();
                var comments = "/api/v1/comment/" + $(this).prevAll(':hidden').val() + "/"
                var data = JSON.stringify({"message": m, "fuck": comments});
                $.ajax({
                    url:'/api/v1/comment/',
                    type: 'POST',
                    data: data,
                    contentType:"application/json; charset=utf-8",
                    dataType: 'json',
                    success: function() {
                        $(this).parent().hide();
                    }
                })
            });

        });
    </script>
</head>
<body>
    <div class="FuckList">
        <h1>Fuck You</h1>
    {% block content %}
    </div>
    {% endblock %}
</body>
</html>

templates/fuck_detail.html
{% extends 'base.html'%}
{% block content %}
    <div>
        {{ object.message }}
    </div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block content %}
    <ul>
        {% for fuck in object_list %}
            <li>
                <div class="fuckitem">
                    <p class="fuck">{{ fuck.message }}</p>

                    <p class="fuckauthor">{{ fuck.author }}</p>

                    <p>{{ fuck.modified_date }}</p>

                    <div class="comments">
                        {% for comment in fuck.comment_set.all %}
                            <h3>{{ comment.message }}</h3>
                            <p>{{ comment.author }}</p>
                            {% if request.user == comment.author %}
                                <a href="/editComment">Edit Comment</a>
                            {% endif %}
                        {% endfor %}
                    </div>
                    <a href="#" class="AddCommentButton">add comment</a>

                    <div class="addComment" style="display:none">
                        <input type="hidden" value="{{ fuck.id}}" />
                        <textarea class="TextAreaComment">

                        </textarea>
                        <a href="#" class="SubmitComment">Submit comment</a>
                    </div>
                    {% if request.user == fuck.author %}
                        <a href="/editFuck">Edit</a>
                    {% endif %}
                </div>
            </li>
        {% endfor %}
        {% if is_paginated %}
            <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="/?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="/?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
            </div>
        {% endif %}
    </ul>
    <a href="/newfuck">Fuck You...</a>
{% endblock %}

templates/newfuck.html
{% extends 'base.html' %}
{% block content %}
<form action="" method='post'>{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Fuck You"/>
</form>
{% endblock %}